apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: istio-system
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    # TODO
    email: your email
    server: acme server
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt
    solvers:
    - dns01:
        clouddns:
          # TODO
          # The ID of the GCP project
          project: your gcp project
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-noctchill-dev
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    # The issuer created previously
    name: letsencrypt
    kind: Issuer
  dnsNames:
  # TODO
  - your dns name
